# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('square', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.IntegerField()),
                ('price', models.IntegerField()),
                ('price_by_m', models.IntegerField()),
                ('url', models.URLField()),
                ('address', models.TextField()),
                ('distance', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('total_floors', models.IntegerField()),
                ('source_type', models.CharField(max_length=255)),
                ('source_id', models.IntegerField()),
            ],
        ),
    ]
