# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_flat_metro'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='real_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
