# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_flat_real_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='debug_url',
            field=models.TextField(blank=True),
        ),
    ]
